### ISSUE TITLE
Blog usage sidebar "Most commented posts" JS error: statsupdate_killspinner is not a function

### ISSUE THREAD

**Issue by mwithheld** [moodleou/moodle-mod_oublog#98] opened 2019-05-16 19:17 UTC
Seen on Moodle 3.5.5 (Build: 20190311) using OUBlog version:
```
$plugin->version = 2018032001;
$plugin->requires = 2017111300;
$plugin->component = 'mod_oublog';// Full name of the plugin (used for diagnostics)
$plugin->maturity = MATURITY_STABLE;
$plugin->release = '3.4 r1';
```

To reproduce:

- In a course, create a Blog activity
- In the "Blog usage" sidebar, click "Most commented posts" and click the Update button in the block.
- The JS console will show an error:

JS console for url https://some.moodlesite.com/mod/oublog/view.php?id=1192592&forceview=1

```
yui_combo.php?m/1556911031/mod_oublog/statsupdate/statsupdate-debug.js:69 
Uncaught TypeError: statsupdate_killspinner is not a function
    at YUI.failure (yui_combo.php?m/1556911031/mod_oublog/statsupdate/statsupdate-debug.js:69)
    at Y.Subscriber._notify (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13680)
    at Y.Subscriber.notify (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13709)
    at Y.CustomEvent._notify (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13372)
    at Y.CustomEvent._procSubs (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13498)
    at Y.CustomEvent.fireSimple (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13465)
    at Y.CustomEvent._fire (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:13447)
    at IO.fire (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:14600)
    at IO._evt (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:23686)
    at IO.failure (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:23774)
```

**Comment by jason-platts** [comment] 2019-05-17 07:24
Thanks for reporting but this is a duplicate of #88 
(Seems this button has an issue when using Boost)

**Closed by jason-platts** 2019-05-17 07:24 UTC
